import { NodeType, NodeConfig } from "./index";

export const NODE_TYPES = NodeType;

export const SELENIUM_SELECTORS = [
  { value: "id", label: "ID" },
  { value: "name", label: "Name" },
  { value: "class_name", label: "Class Name" },
  { value: "tag_name", label: "Tag Name" },
  { value: "xpath", label: "XPath" },
  { value: "css_selector", label: "CSS Selector" },
  { value: "link_text", label: "Link Text" },
  { value: "partial_link_text", label: "Partial Link Text" },
];

export const WAIT_CONDITIONS = [
  { value: "presence_of_element_located", label: "Elemento Presente" },
  { value: "visibility_of_element_located", label: "Elemento Visível" },
  { value: "element_to_be_clickable", label: "Elemento Clicável" },
  { value: "invisibility_of_element_located", label: "Elemento Invisível" },
  {
    value: "text_to_be_present_in_element",
    label: "Texto Presente no Elemento",
  },
  { value: "element_to_be_selected", label: "Elemento Selecionado" },
];

export const getNodeConfig = (type: NodeType): NodeConfig | null => {
  const configs: Record<NodeType, NodeConfig> = {
    [NodeType.LOGIN]: {
      label: "Navegação/Login",
      description: "Abre o navegador, acessa uma URL e realiza login automaticamente preenchendo usuário e senha.",
      icon: "LogIn",
      color: "bg-blue-600",
      inputs: [
        {
          name: "url",
          label: "URL",
          type: "text",
          placeholder: "https://exemplo.com",
          helpText: "Endereço do site que você deseja acessar.",
          required: true,
        },
        {
          name: "username_selector_type",
          label: "Tipo Seletor Usuário",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Como encontrar o campo de usuário (ID, Name, XPath, etc). Recomendado: ID.",
        },
        {
          name: "username_selector",
          label: "Seletor do Campo Usuário",
          type: "text",
          placeholder: 'usuario, #login, //input[@name="user"]',
          helpText: "O valor do seletor. Ex: se for ID, coloque o ID do elemento.",
        },
        {
          name: "username_value",
          label: "Valor do Usuário",
          type: "text",
          placeholder: "seu_usuario",
          helpText: "O nome de usuário ou e-mail para login.",
        },
        {
          name: "password_selector_type",
          label: "Tipo Seletor Senha",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Como encontrar o campo de senha.",
        },
        {
          name: "password_selector",
          label: "Seletor do Campo Senha",
          type: "text",
          placeholder: 'senha, #password, //input[@type="password"]',
          helpText: "O valor do seletor do campo de senha.",
        },
        {
          name: "password_value",
          label: "Valor da Senha",
          type: "password",
          placeholder: "sua_senha",
          helpText: "A senha para realizar o login.",
        },
        {
          name: "login_button_selector_type",
          label: "Tipo Seletor Botão",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Como encontrar o botão de login/entrar.",
        },
        {
          name: "login_button_selector",
          label: "Seletor do Botão Login",
          type: "text",
          placeholder: 'btn_login, #submit, //input[@type="submit"]',
          helpText: "O seletor do botão que envia o formulário.",
        },
        {
          name: "wait_time",
          label: "Tempo de Espera (s)",
          type: "number",
          placeholder: "10",
          helpText: "Tempo máximo para aguardar os elementos aparecerem.",
        },
      ],
    },
    [NodeType.OPEN_SITE]: {
      label: "Acessar Site",
      description: "Apenas navega para uma URL específica sem realizar login.",
      icon: "LogIn",
      color: "bg-pink-600",
      inputs: [
        {
          name: "url",
          label: "URL",
          type: "text",
          placeholder: "https://exemplo.com",
          helpText: "Endereço do site para acessar.",
          required: true,
        },
        {
          name: "wait_time",
          label: "Tempo de Espera (s)",
          type: "number",
          placeholder: "10",
          helpText: "Tempo para aguardar após o carregamento.",
        },
      ],
    },
    [NodeType.CLICK_BUTTON]: {
      label: "Clicar Elemento",
      description: "Simula um clique (ou duplo clique) em qualquer elemento da página, como botões, links ou abas.",
      icon: "MousePointer",
      color: "bg-green-600",
      inputs: [
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Método para identificar o elemento a ser clicado.",
          required: true,
        },
        {
          name: "selector_value",
          label: "Valor do Seletor",
          type: "text",
          placeholder: 'btn_pesquisar, #submit, //button[text()="Clique"]',
          helpText: "O identificador do elemento. Use XPath para cliques mais complexos.",
          required: true,
        },
        {
          name: "wait_condition",
          label: "Condição de Espera",
          type: "select",
          placeholder: "",
          options: WAIT_CONDITIONS,
          helpText: "Estado que o elemento deve ter antes de tentar clicar.",
        },
        {
          name: "wait_timeout",
          label: "Timeout (s)",
          type: "number",
          placeholder: "10",
          helpText: "Tempo máximo aguardando o elemento ficar clicável.",
        },
        {
          name: "scroll_to_element",
          label: "Rolar até Elemento",
          type: "checkbox",
          placeholder: "",
          helpText: "Se marcado, a página rolará até o elemento antes de clicar.",
        },
        {
          name: "double_click",
          label: "Duplo Clique",
          type: "checkbox",
          placeholder: "",
          helpText: "Realiza um clique duplo em vez de um clique simples.",
        },
        {
          name: "pause_after",
          label: "Pausa Após Clique (s)",
          type: "number",
          placeholder: "1",
          helpText: "Pausa opcional após a ação para aguardar carregamentos.",
        },
      ],
    },
    [NodeType.EXTRACT_TABLE]: {
      label: "Inserir Texto/Dados",
      description: "Digita texto em campos de formulário ou inputs.",
      icon: "Type",
      color: "bg-purple-600",
      inputs: [
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Método para encontrar o campo de texto.",
          required: true,
        },
        {
          name: "selector_value",
          label: "Valor do Seletor",
          type: "text",
          placeholder: 'nu_cns, #cpf, //input[@name="documento"]',
          helpText: "Identificador do campo onde o texto será digitado.",
          required: true,
        },
        {
          name: "text_value",
          label: "Texto a Inserir",
          type: "text",
          placeholder: "Texto ou variável ${cpf}",
          helpText: "O valor a ser digitado. Aceita variáveis como ${variavel}.",
          required: true,
        },
        {
          name: "clear_before",
          label: "Limpar Campo Antes",
          type: "checkbox",
          placeholder: "",
          helpText: "Apaga qualquer texto existente no campo antes de digitar.",
        },
        {
          name: "wait_condition",
          label: "Condição de Espera",
          type: "select",
          placeholder: "",
          options: WAIT_CONDITIONS,
          helpText: "Estado do campo antes da interação.",
        },
        {
          name: "wait_timeout",
          label: "Timeout (s)",
          type: "number",
          placeholder: "10",
        },
        {
          name: "press_enter",
          label: "Pressionar Enter",
          type: "checkbox",
          placeholder: "",
          helpText: "Pressiona a tecla ENTER após digitar o texto.",
        },
        {
          name: "pause_after",
          label: "Pausa Após Inserção (s)",
          type: "number",
          placeholder: "0.5",
        },
      ],
    },
    [NodeType.WAIT]: {
      label: "Aguardar Elemento",
      description: "Pausa a execução até que um elemento apareça, desapareça ou um tempo fixo passe.",
      icon: "Clock",
      color: "bg-orange-600",
      inputs: [
        {
          name: "wait_type",
          label: "Tipo de Espera",
          type: "select",
          placeholder: "",
          options: [
            { value: "time", label: "Tempo Fixo" },
            { value: "element", label: "Aguardar Elemento" },
            { value: "condition", label: "Condição Específica" },
          ],
          helpText: "Escolha entre esperar segundos fixos ou um evento na página.",
          required: true,
        },
        {
          name: "duration",
          label: "Duração (s)",
          type: "number",
          placeholder: "5",
          helpText: "Usado apenas para 'Tempo Fixo'.",
        },
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Como identificar o elemento aguardado.",
        },
        {
          name: "selector_value",
          label: "Valor do Seletor",
          type: "text",
          placeholder: 'elemento, #loading, //div[@class="result"]',
          helpText: "O elemento a ser monitorado.",
        },
        {
          name: "wait_condition",
          label: "Condição de Espera",
          type: "select",
          placeholder: "",
          options: WAIT_CONDITIONS,
          helpText: "O que deve acontecer com o elemento (aparecer, sumir, etc).",
        },
        {
          name: "timeout",
          label: "Timeout Máximo (s)",
          type: "number",
          placeholder: "30",
          helpText: "Tempo máximo de espera antes de dar erro.",
        },
        {
          name: "expected_text",
          label: "Texto Esperado (opcional)",
          type: "text",
          placeholder: "Texto que deve aparecer",
          helpText: "Se preenchido, espera até que o elemento contenha este texto específico.",
        },
        {
          name: "retry_attempts",
          label: "Tentativas de Retry",
          type: "number",
          placeholder: "3",
          helpText: "Quantas vezes tentar verificar novamente se falhar.",
        },
      ],
    },
    [NodeType.SLEEP]: {
      label: "Pausa (Sleep)",
      description: "Uma pausa simples e incondicional na execução.",
      icon: "Timer",
      color: "bg-indigo-600",
      inputs: [
        {
          name: "duration",
          label: "Duração da Pausa (segundos)",
          type: "number",
          placeholder: "2.5",
          helpText: "Tempo em segundos para pausar.",
          required: true,
        },
        {
          name: "description",
          label: "Descrição (opcional)",
          type: "text",
          placeholder: "Aguardar carregamento da página",
          helpText: "Uma nota para lembrar o motivo desta pausa.",
        },
      ],
    },
    [NodeType.SPREADSHEET]: {
      label: "Planilha (Excel/CSV)",
      description: "Lê, cria ou salva planilhas Excel (.xlsx) ou CSV.",
      icon: "FileSpreadsheet",
      color: "bg-emerald-600",
      inputs: [
        {
          name: "operation",
          label: "Operação",
          type: "select",
          placeholder: "",
          options: [
            { value: "read", label: "Ler Planilha" },
            { value: "create", label: "Criar Planilha" },
            { value: "write", label: "Escrever Dados" },
            { value: "save", label: "Salvar Planilha" },
          ],
          helpText: "Ação a ser realizada com a planilha.",
          required: true,
        },
        {
          name: "file_path",
          label: "Caminho do Arquivo",
          type: "text",
          placeholder: "C:/dados/planilha.xlsx ou dados.csv",
          helpText: "Localização do arquivo no computador.",
          required: true,
        },
        {
          name: "sheet_name",
          label: "Nome da Aba (Excel)",
          type: "text",
          placeholder: "Sheet1",
          helpText: "Nome da aba específica se for um arquivo Excel.",
        },
        {
          name: "variable_name",
          label: "Nome da Variável",
          type: "text",
          placeholder: "df_dados",
          helpText: "Nome da variável onde os dados da planilha serão armazenados.",
          required: true,
        },
        {
          name: "columns",
          label: "Colunas (separadas por vírgula)",
          type: "text",
          placeholder: "Nome, Email, Telefone",
          helpText: "Para criar ou filtrar, especifique as colunas.",
        },
        {
          name: "include_index",
          label: "Incluir Índice",
          type: "checkbox",
          placeholder: "",
          helpText: "Se marcado, inclui o índice ao salvar.",
        },
        {
          name: "include_header",
          label: "Incluir Cabeçalho",
          type: "checkbox",
          placeholder: "",
          helpText: "Se marcado, inclui os nomes das colunas como primeira linha.",
        },
        {
          name: "extra_column_name",
          label: "Nome Coluna Extra (opcional)",
          type: "text",
          placeholder: "Competência",
          helpText: "Adiciona uma nova coluna com um valor fixo ao salvar.",
        },
        {
          name: "extra_column_value",
          label: "Valor Coluna Extra",
          type: "text",
          placeholder: "02-2025",
          helpText: "O valor fixo para a coluna extra.",
        },
        {
          name: "extra_column_position",
          label: "Posição Coluna Extra",
          type: "number",
          placeholder: "1",
          helpText: "Posição numérica onde inserir a coluna extra (1 = primeira).",
        },
        {
          name: "filter_column",
          label: "Coluna para Filtrar",
          type: "text",
          placeholder: "Status",
          helpText: "Filtra linhas onde esta coluna tem determinado valor.",
        },
        {
          name: "filter_value",
          label: "Valor do Filtro",
          type: "text",
          placeholder: "Ativo",
          helpText: "Valor que a coluna deve ter para manter a linha.",
        },
      ],
    },
    [NodeType.LOOP_FOR]: {
      label: "Loop For (Repetir)",
      description: "Repete uma sequência de ações um número fixo de vezes ou para cada item de uma lista/planilha.",
      icon: "RotateCw",
      color: "bg-cyan-600",
      inputs: [
        {
          name: "loop_type",
          label: "Tipo de Loop",
          type: "select",
          placeholder: "",
          options: [
            { value: "dataframe_rows", label: "Linhas da Planilha" },
            { value: "range", label: "Intervalo Numérico" },
            { value: "list", label: "Lista de Valores" },
          ],
          helpText: "Define sobre o que o loop irá iterar.",
          required: true,
        },
        {
          name: "dataframe_variable",
          label: "Variável da Planilha",
          type: "text",
          placeholder: "df_dados",
          helpText: "Nome da variável que contém a planilha (Dataframe).",
        },
        {
          name: "row_variable",
          label: "Variável da Linha Atual",
          type: "text",
          placeholder: "linha_atual",
          helpText: "Nome da variável que receberá os dados da linha atual em cada iteração.",
        },
        {
          name: "start_value",
          label: "Valor Inicial",
          type: "number",
          placeholder: "0",
          helpText: "Início do intervalo numérico.",
        },
        {
          name: "end_value",
          label: "Valor Final",
          type: "number",
          placeholder: "10",
          helpText: "Fim do intervalo numérico.",
        },
        {
          name: "step_value",
          label: "Incremento",
          type: "number",
          placeholder: "1",
          helpText: "Quanto adicionar a cada passo (padrão 1).",
        },
        {
          name: "list_values",
          label: "Lista de Valores",
          type: "text",
          placeholder: "valor1, valor2, valor3",
          helpText: "Lista de valores separados por vírgula para iterar.",
        },
        {
          name: "max_iterations",
          label: "Máximo de Iterações",
          type: "number",
          placeholder: "1000",
          helpText: "Segurança para evitar loops infinitos.",
        },
      ],
    },
    [NodeType.LOOP_WHILE]: {
      label: "Loop While (Enquanto)",
      description: "Repete ações enquanto uma condição for verdadeira.",
      icon: "Repeat",
      color: "bg-teal-600",
      inputs: [
        {
          name: "condition_type",
          label: "Tipo de Condição",
          type: "select",
          placeholder: "",
          options: [
            { value: "variable_comparison", label: "Comparar Variável" },
            { value: "element_exists", label: "Elemento Existe" },
            { value: "custom", label: "Condição Personalizada" },
          ],
          helpText: "A regra que mantém o loop rodando.",
          required: true,
        },
        {
          name: "variable_name",
          label: "Nome da Variável",
          type: "text",
          placeholder: "contador",
          helpText: "Variável a ser comparada.",
        },
        {
          name: "comparison_operator",
          label: "Operador",
          type: "select",
          placeholder: "",
          options: [
            { value: "<", label: "Menor que (<)" },
            { value: "<=", label: "Menor ou igual (<=)" },
            { value: ">", label: "Maior que (>)" },
            { value: ">=", label: "Maior ou igual (>=)" },
            { value: "==", label: "Igual (==)" },
            { value: "!=", label: "Diferente (!=)" },
          ],
          helpText: "Como comparar a variável com o valor.",
        },
        {
          name: "comparison_value",
          label: "Valor de Comparação",
          type: "text",
          placeholder: "10",
          helpText: "Valor alvo para comparação.",
        },
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Para verificar existência de elemento.",
        },
        {
          name: "selector_value",
          label: "Seletor do Elemento",
          type: "text",
          placeholder: "#loading, .spinner",
          helpText: "Identificador do elemento a verificar.",
        },
        {
          name: "custom_condition",
          label: "Condição Python",
          type: "text",
          placeholder: "len(lista) > 0",
          helpText: "Expressão Python que retorna True ou False.",
        },
        {
          name: "max_iterations",
          label: "Máximo de Iterações",
          type: "number",
          placeholder: "100",
          helpText: "Limite de segurança.",
        },
      ],
    },
    [NodeType.VARIABLE]: {
      label: "Variável",
      description: "Gerencia variáveis: cria, atualiza, incrementa ou concatena valores.",
      icon: "Hash",
      color: "bg-amber-600",
      inputs: [
        {
          name: "operation",
          label: "Operação",
          type: "select",
          placeholder: "",
          options: [
            { value: "set", label: "Definir Valor" },
            { value: "get_cell", label: "Obter Célula da Planilha" },
            { value: "increment", label: "Incrementar" },
            { value: "concatenate", label: "Concatenar Texto" },
          ],
          helpText: "O que você deseja fazer com a variável.",
          required: true,
        },
        {
          name: "variable_name",
          label: "Nome da Variável",
          type: "text",
          placeholder: "minha_variavel",
          helpText: "O nome identificador da variável (sem espaços).",
          required: true,
        },
        {
          name: "variable_value",
          label: "Valor",
          type: "text",
          placeholder: "Valor inicial",
          helpText: "Valor a ser atribuído (usado em 'Definir Valor').",
        },
        {
          name: "dataframe_variable",
          label: "Variável da Planilha",
          type: "text",
          placeholder: "df_dados",
          helpText: "Nome da variável que contém o dataframe (para 'Obter Célula').",
        },
        {
          name: "row_variable",
          label: "Variável da Linha",
          type: "text",
          placeholder: "linha_atual",
          helpText: "Objeto da linha atual (para 'Obter Célula' dnetro de loop).",
        },
        {
          name: "column_name",
          label: "Nome da Coluna",
          type: "text",
          placeholder: "Nome",
          helpText: "Nome da coluna para extrair o valor.",
        },
        {
          name: "increment_value",
          label: "Valor do Incremento",
          type: "number",
          placeholder: "1",
          helpText: "Quanto somar ao valor atual (para 'Incrementar').",
        },
        {
          name: "text_to_add",
          label: "Texto para Concatenar",
          type: "text",
          placeholder: " - processado",
          helpText: "Texto a ser adicionado ao final (para 'Concatenar').",
        },
      ],
    },
    [NodeType.CONDITION]: {
      label: "Condição (If/Else)",
      description: "Cria um desvio no fluxo baseado em uma verificação lógica (Se/Senão).",
      icon: "GitBranch",
      color: "bg-rose-600",
      inputs: [
        {
          name: "condition_type",
          label: "Tipo de Condição",
          type: "select",
          placeholder: "",
          options: [
            { value: "variable_comparison", label: "Comparar Variável" },
            { value: "element_exists", label: "Elemento Existe" },
            { value: "text_contains", label: "Texto Contém" },
            { value: "custom", label: "Condição Personalizada" },
          ],
          helpText: "O critério para decidir qual caminho seguir.",
          required: true,
        },
        {
          name: "variable_name",
          label: "Nome da Variável",
          type: "text",
          placeholder: "status",
          helpText: "Variável a ser avaliada.",
        },
        {
          name: "comparison_operator",
          label: "Operador",
          type: "select",
          placeholder: "",
          options: [
            { value: "==", label: "Igual (==)" },
            { value: "!=", label: "Diferente (!=)" },
            { value: "<", label: "Menor que (<)" },
            { value: "<=", label: "Menor ou igual (<=)" },
            { value: ">", label: "Maior que (>)" },
            { value: ">=", label: "Maior ou igual (>=)" },
            { value: "in", label: "Contém (in)" },
            { value: "not in", label: "Não contém (not in)" },
          ],
          helpText: "Lógica de comparação.",
        },
        {
          name: "comparison_value",
          label: "Valor de Comparação",
          type: "text",
          placeholder: "Ativo",
          helpText: "Valor esperado.",
        },
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Para verificar se algo existe na página.",
        },
        {
          name: "selector_value",
          label: "Seletor do Elemento",
          type: "text",
          placeholder: "#success, .error",
          helpText: "O elemento a buscar.",
        },
        {
          name: "text_source",
          label: "Fonte do Texto",
          type: "text",
          placeholder: "variavel_texto",
          helpText: "Variável contendo o texto onde buscar (para 'Texto Contém').",
        },
        {
          name: "search_text",
          label: "Texto a Procurar",
          type: "text",
          placeholder: "sucesso",
          helpText: "O trecho de texto que você procura.",
        },
        {
          name: "custom_condition",
          label: "Condição Python",
          type: "text",
          placeholder: 'variavel > 0 and status == "ok"',
          helpText: "Expressão lógica avançada em Python.",
        },
      ],
    },
    [NodeType.CAPTURE_TABLE]: {
      label: "Capturar Tabela",
      description: "Extrai dados de uma tabela HTML da página e salva como uma planilha (Dataframe).",
      icon: "Table",
      color: "bg-yellow-600",
      inputs: [
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Como encontrar a tabela.",
          required: true,
        },
        {
          name: "selector_value",
          label: "Seletor da Tabela",
          type: "text",
          placeholder: '//table[@class="table_listagem"], #tabela, .data-table',
          helpText: "Identificador da tabela `<table>`.",
          required: true,
        },
        {
          name: "variable_name",
          label: "Nome da Variável",
          type: "text",
          placeholder: "df_tabela",
          helpText: "Onde salvar os dados capturados.",
          required: true,
        },
        {
          name: "include_headers",
          label: "Incluir Cabeçalho",
          type: "checkbox",
          placeholder: "",
          helpText: "Se marcado, usa a primeira linha da tabela como nomes das colunas.",
        },
        {
          name: "wait_condition",
          label: "Condição de Espera",
          type: "select",
          placeholder: "",
          options: WAIT_CONDITIONS,
          helpText: "Aguardar a tabela estar visível ou presente.",
        },
        {
          name: "wait_timeout",
          label: "Timeout (s)",
          type: "number",
          placeholder: "10",
        },
        {
          name: "skip_empty_rows",
          label: "Pular Linhas Vazias",
          type: "checkbox",
          placeholder: "",
          helpText: "Não captura linhas que não tenham conteúdo.",
        },
      ],
    },
    [NodeType.SCHEDULE]: {
      label: "Agendamento",
      description: "Define regras para execução automática deste fluxo em horários específicos.",
      icon: "Calendar",
      color: "bg-violet-600",
      inputs: [
        {
          name: "schedule_type",
          label: "Tipo de Agendamento",
          type: "select",
          placeholder: "",
          options: [
            { value: "daily", label: "Diário" },
            { value: "weekly", label: "Semanal" },
            { value: "monthly", label: "Mensal" },
            { value: "interval", label: "Intervalo" },
            { value: "cron", label: "Expressão Cron" },
          ],
          helpText: "Frequência da execução.",
          required: true,
        },
        {
          name: "time",
          label: "Horário (HH:MM)",
          type: "text",
          placeholder: "09:00",
          helpText: "Hora da execução (para Diário, Semanal, Mensal).",
        },
        {
          name: "days_of_week",
          label: "Dias da Semana",
          type: "select",
          placeholder: "",
          options: [
            { value: "monday", label: "Segunda-feira" },
            { value: "tuesday", label: "Terça-feira" },
            { value: "wednesday", label: "Quarta-feira" },
            { value: "thursday", label: "Quinta-feira" },
            { value: "friday", label: "Sexta-feira" },
            { value: "saturday", label: "Sábado" },
            { value: "sunday", label: "Domingo" },
          ],
          helpText: "Dias específicos para execução semanal.",
        },
        {
          name: "days_of_month",
          label: "Dias do Mês (1-31)",
          type: "text",
          placeholder: "1,15,30",
          helpText: "Dias específicos para execução mensal.",
        },
        {
          name: "interval_minutes",
          label: "Intervalo (minutos)",
          type: "number",
          placeholder: "60",
          helpText: "Executar a cada X minutos.",
        },
        {
          name: "cron_expression",
          label: "Expressão Cron",
          type: "text",
          placeholder: "0 9 * * 1-5",
          helpText: "Sintaxe avançada de agendamento (min hora dia mês dia_semana).",
        },
        {
          name: "timezone",
          label: "Fuso Horário",
          type: "text",
          placeholder: "America/Sao_Paulo",
          helpText: "Fuso para interpretar o horário.",
        },
        {
          name: "start_date",
          label: "Data de Início",
          type: "text",
          placeholder: "2024-01-01",
          helpText: "Quando começar a valer o agendamento.",
        },
        {
          name: "end_date",
          label: "Data de Fim (opcional)",
          type: "text",
          placeholder: "2024-12-31",
          helpText: "Quando parar o agendamento.",
        },
        {
          name: "max_executions",
          label: "Máximo de Execuções",
          type: "number",
          placeholder: "100",
          helpText: "Limite total de vezes que pode rodar.",
        },
      ],
    },
    [NodeType.EXECUTE_SCRIPT]: {
      label: "Executar Script JS",
      description: "Executa código JavaScript personalizado no navegador.",
      icon: "Code",
      color: "bg-red-600",
      inputs: [
        {
          name: "script",
          label: "Script JavaScript",
          type: "text",
          placeholder: "return document.title;",
          helpText: "O código JS a ser executado. Use 'return' para retornar valor.",
          required: true,
        },
        {
          name: "variable_name",
          label: "Variável de Saída",
          type: "text",
          placeholder: "resultado_script",
          helpText: "Variável onde o resultado do script será salvo.",
        },
      ],
    },
    [NodeType.EXTRACT_TEXT]: {
      label: "Extrair Texto (Regex)",
      description: "Busca e extrai padrões de texto específicos usando Lógica Regular (Regex).",
      icon: "Search",
      color: "bg-pink-500",
      inputs: [
        {
          name: "selector_type",
          label: "Tipo de Seletor",
          type: "select",
          placeholder: "",
          options: SELENIUM_SELECTORS,
          helpText: "Onde buscar o texto (elemento específico).",
        },
        {
          name: "selector_value",
          label: "Valor do Seletor",
          type: "text",
          placeholder: "//div[@id='content']",
          helpText: "Seletor do elemento. Deixe vazio para buscar na página toda (se habilitado fallback).",
        },
        {
          name: "regex_pattern",
          label: "Padrão Regex",
          type: "text",
          placeholder: "Valor: (\\d+)",
          helpText: "Expressão Regular para capturar o dado desejado. Use parênteses para captura.",
          required: true,
        },
        {
          name: "variable_name",
          label: "Variável de Saída",
          type: "text",
          placeholder: "texto_extraido",
          helpText: "Onde salvar o texto encontrado.",
          required: true,
        },
        {
          name: "post_extract_regex_pattern", // Renamed from regex_pattern to avoid conflict and clarify intent
          label: "Padrão Regex (opcional)",
          type: "text",
          placeholder: "(\\d{2}/\\d{2}/\\d{4})",
          helpText: "Se preenchido, aplica regex no texto extraído. Use grupos () para extrair partes específicas.",
        },
        {
          name: "fallback_to_body",
          label: "Buscar no Body se falhar",
          type: "checkbox",
          placeholder: "",
          helpText: "Se ativado, caso o seletor falhe, busca o regex em toda a página.",
        },
        {
          name: "fallback_regex_pattern",
          label: "Regex de Fallback (opcional)",
          type: "text",
          placeholder: "Data:\\s*(\\d{2}/\\d{2}/\\d{4})",
          helpText: "Regex alternativo para usar na busca do Body.",
        },
        {
          name: "wait_timeout",
          label: "Timeout (s)",
          type: "number",
          placeholder: "10",
        },
      ],
    },
    [NodeType.CLOSE_BROWSER]: {
      label: "Fechar Navegador",
      description: "Encerra a instância do navegador e limpa os recursos.",
      icon: "XCircle", 
      color: "bg-red-600",
      inputs: [],
    },
    [NodeType.TRANSFORM_COLUMN]: {
      label: "Transformar Coluna",
      description: "Aplica transformações em colunas de uma planilha (Dataframe).",
      icon: "Columns",
      color: "bg-teal-500",
      inputs: [
        {
          name: "dataframe_variable",
          label: "Variável DataFrame",
          type: "text",
          placeholder: "df",
          helpText: "A planilha que contém a coluna.",
          required: true,
        },
        {
          name: "column_name",
          label: "Nome da Coluna",
          type: "text",
          placeholder: "coluna_original",
          helpText: "A coluna a ser transformada.",
          required: true,
        },
        {
          name: "transformation_type",
          label: "Tipo Transformação",
          type: "select",
          placeholder: "",
          options: [
            { value: "first_letter_upper", label: "Primeira Letra Maiúscula" },
            { value: "parse_list", label: "Parse String p/ Lista" },
            { value: "limit_list", label: "Limitar Lista" },
            { value: "to_string", label: "Converter p/ String" },
          ],
          helpText: "Qual operação realizar nos dados da coluna.",
          required: true,
        },
        {
          name: "new_column_name",
          label: "Nova Coluna (opcional)",
          type: "text",
          placeholder: "coluna_nova",
          helpText: "Se preenchido, cria uma nova coluna em vez de substituir a original.",
        },
        {
          name: "limit",
          label: "Limite (para listas)",
          type: "number",
          placeholder: "4",
          helpText: "Quantidade máxima de itens se for uma lista.",
        },
      ],
    },
    [NodeType.GROUP_DATA]: {
      label: "Agrupar Dados",
      description: "Agrupa linhas de uma planilha com base em uma coluna e agrega valores.",
      icon: "Layers",
      color: "bg-indigo-500",
      inputs: [
        {
          name: "dataframe_variable",
          label: "Variável DataFrame",
          type: "text",
          placeholder: "df",
          required: true,
        },
        {
          name: "group_by_column",
          label: "Agrupar Por",
          type: "text",
          placeholder: "coluna_grupo",
          helpText: "A coluna usada para agrupar (ex: 'Categoria').",
          required: true,
        },
        {
          name: "aggregations",
          label: "Agregações (col:func)",
          type: "text",
          placeholder: "id:size, valor:sum",
          helpText: "Como resumir as outras colunas. Ex: 'vendas:sum'.",
          required: true,
        },
        {
          name: "output_variable",
          label: "Variável de Saída",
          type: "text",
          placeholder: "df_agrupado",
          helpText: "Nova variável para guardar o resultado agrupado.",
          required: true,
        },
      ],
    },
    [NodeType.EXECUTE_PYTHON]: {
      label: "Código Python",
      description: "Executa código Python arbitrário com acesso total ao ambiente (White Label).",
      icon: "Terminal",
      color: "bg-slate-700",
      inputs: [
        {
          name: "code",
          label: "Código Python",
          type: "text",
          placeholder: "variables['novo_valor'] = int(variables['valor']) * 2",
          helpText: "Seu código Python. Use 'driver', 'variables', 'dataframes' diretamente.",
          required: true,
        },
      ],
    },
  };

  return configs[type] || null;
};
